[build]
  functions = "netlify/functions"
  publish = "."

# Configuração para as funções serverless
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Headers globais para CORS
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# Redirecionamentos para a função da API
[[redirects]]
  from = "/api/cartola/*"
  to = "/.netlify/functions/cartola-api?endpoint=:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/cartola"
  to = "/.netlify/functions/cartola-api"
  status = 200
  force = true

# Headers específicos para a API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Configurações de cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Headers para arquivos CSV
[[headers]]
  for = "/*.csv"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/csv"

# Configuração para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["!US"]}
  force = false
